#!/bin/bash

# IF-ELSE
echo "Check your dir..."
if pwd; then
	echo "Your dir is exist"
fi

# Check user in all users
user=foo

if grep $user /etc/passwd; then
	echo "The user $user is exist"
elif ls /home; then
	echo "The user $user doesn't exist but anyway there is a directory under /home"
fi
