#!/bin/bash

echo "Current directory is:"
pwd
echo "Current user is:"
whoami
echo "Home is current user is: $HOME"
echo "Test dollar \$1"

# USER VARIABLES
name=$USER
age=22
mydir=$(pwd)

echo "Welcome to sh $name. Oh, you're age $age"
echo "mydir = $mydir"

# MATH OPERATIONS
a=4
b=7
var1=$((a+b))
var2=$((b-a))

echo "var1 = $var1"
echo "var2 = $var2"
